#!/usr/bin/env node
/**
 * Bundle scripts/install.sh into src/script.generated.js at Worker build time.
 * The Cloudflare endpoint never proxies an unpinned raw main branch script.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const installPath = join(root, "scripts", "install.sh");
const outDir = join(here, "src");
const outPath = join(outDir, "script.generated.js");

const script = readFileSync(installPath, "utf8");
if (!script.startsWith("#!/")) {
  console.error("install.sh does not look like a shell script");
  process.exit(1);
}
if (!script.includes("Installing Rivora")) {
  console.error("install.sh missing expected content marker");
  process.exit(1);
}

mkdirSync(outDir, { recursive: true });
const generated = `// AUTO-GENERATED by build.mjs — do not edit.
// Source: scripts/install.sh
export const INSTALL_SCRIPT = ${JSON.stringify(script)};
`;
writeFileSync(outPath, generated, "utf8");
console.log(`Embedded ${script.length} bytes from scripts/install.sh → ${outPath}`);
